# Site settings
title: Magick Codes
email: lifewinning@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A conference on magic (with a k or otherwise) and technology.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://magick.codes" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
