# Site settings
title: Magick Codes
email: lifewinning@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An effort to understand how we live with magick, how we live with machines, and what it means to live with both.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://magick.codes" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
